
# fmt: skip file

```{r}


library(ggplot2)
library(forcats)

bd_df <- sumdf_prac |> 
  dplyr::filter(
          year %in% c("2023", "2022"),
          statistic == "Total",
          metric == "Production value"
          # variable == "All production"
        )

# making a barchart
barchart <- ggplot(data = bd_df, 
                   aes(x = fct_reorder(variable, value), 
                                           y = value, fill = factor(year))) +
  # adding count text to each bar
  geom_col(position = "dodge") +
  labs(fill = "Year", 
       x = "", 
       y = "Millions") +
  scale_fill_manual(values = c("blue", "pink")) +
  scale_y_continuous(limits = c(0, 800)) +
  scale_x_discrete(labels = c(
      "All production" = "All production",
      "Groundfish production" = "Groundfish production",
      "Pacific whiting" = "Pacific whiting",
      "Non-whiting groundfish" =  "Non-whiting groundfish",
      "Sablefish" = "Sablefish",
      "Rockfish" = "Rockfish",
      "Dover sole" = "Dover sole",
      "Petrale sole" = "Petrale sole",
      "Thornyheads" = "Thornyheads",
      "Other groundfish species" = "Other groundfish species",
       "Other species production" = "Other species production",
        "Crab" = "Crab",
        "Shrimp" = "Shrimp",
        "Salmon" = "Salmon",
        "Tuna" = "Tuna",
        "Coastal pelagics" = "Coastal pelagics",
        "Other shellfish" = "Other shellfish",
        "Other species" = "Other species")) +
  coord_flip() +
  theme(
    # note: need to make these fills as transparent for final figure when stitching together
    # they are colored right now so we can show the bacgkround color in the individual plot
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    # axis 
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.text.y = element_text(color = "black",
                               # family = "sen",
                               # size = 48,
                              hjust = 1,     
                               margin = margin(-10, -20, -50, 0)),
    # axis.text.x = element_blank(),
     axis.ticks.y = element_blank(),
    axis.ticks.x = element_line(color = ),
    
    # grids 
     # panel.grid.major.x = element_line(color = "black", linetype = "dashed"),
    # legend
    legend.position = "none"
  )


# making a barchart with colored background for displaying individually
barchart_filled <- barchart +
  theme(panel.background = element_rect(fill = pal["bg"], color = NA),
    plot.background = element_rect(fill = pal["bg"], color = NA))
```


# radar plot 
```{r}
library(fmsb)
library(ggradar)


radar_df <- proddf_prac |> 
  dplyr::filter(
          year %in% c("2021", "2022"),
          statistic == "Total",
          metric == "Production value",
          variable == "All production"
        )  |> 
  tidyr::pivot_wider(names_from = type, values_from = value) |> 
  dplyr::rename(group = year) |> 
  dplyr::select(c(group, Canned:Unprocessed)) |> 
  dplyr::group_by(group) |> 
  dplyr::summarise(across(c(Canned:Unprocessed), ~ sum(.x, na.rm = TRUE)))

ggradar::ggradar(radar_df)




```


# tree plot

```{r}
library(ggplot2)
library(dplyr)
library(treemapify)


tree_df <- proddf_prac |> 
  dplyr::filter(
          year %in% c("2021", "2022"),
          statistic == "Total",
          metric == "Production value",
          variable == "All production"
        ) 

# making a tree map
tree_fig <-  ggplot2::ggplot(tree_df, ggplot2::aes(area = value, fill = factor(year),
                                 label = factor(year), 
                                 subgroup = type)) +
  # labs(title = "Comparing the World's 10 Largest Fishing Fleets") +
  ggplot2::scale_fill_manual(values = c("#5EB6D9", "darkblue")) +
  treemapify::geom_treemap() +
  treemapify::geom_treemap_subgroup_border(colour = "white", size = 2) +
  treemapify::geom_treemap_subgroup_text(place = "centre", grow = TRUE,
                             alpha = 0.7, 
                             lineheight = 0.3,
                             colour = "white",
                             size = 2) +
  ggplot2::theme(
    panel.background = ggplot2::element_rect(fill = "transparent", color = NA),
    plot.background = ggplot2::element_rect(fill = "transparent", color = NA),
    legend.position = "none")


tree_fig

```

